apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: cmaldonado98/login-microservice:IMAGE_LABEL
          ports:
            - containerPort: 4005
          imagePullPolicy: Always
